<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="scheduler" nsURI="http://www.misc.com/common/moplaf/scheduler/model/0.1"
    nsPrefix="sched">
  <eClassifiers xsi:type="ecore:EClass" name="Scheduler">
    <eOperations name="constructTask" eType="#//SolutionTask">
      <eParameters name="task" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    </eOperations>
    <eOperations name="constructResource" eType="#//SolutionResource">
      <eParameters name="resource" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    </eOperations>
    <eOperations name="enable"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Solutions" upperBound="-1"
        eType="#//Solution" containment="true" eOpposite="#//Solution/Scheduler"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="CurrentSolutionNr" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Tasks" upperBound="-1"
        eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Resources" upperBound="-1"
        eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Solution" eSuperTypes="../../com.misc.common.moplaf.propagator2/model/propagator.ecore#//ObjectWithPropagatorFunctions">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Update the candidate solution with the parameter Move.&#xA;"/>
    </eAnnotations>
    <eOperations name="clone" eType="#//Solution">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Create a new solution in the reset state (no candidate move, candidate values are reset to the solution values)"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="setCandidate">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Set the candidate move. The candidate expression values are updated as a function of the new candidate move."/>
      </eAnnotations>
      <eParameters name="move" eType="#//Move"/>
    </eOperations>
    <eOperations name="resetCandidate">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Reset the candidate solution to this Solution. The candidate expression values are aligned to the solution expression values.&#xA;"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="acceptCandidate">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Change this Solution into the candidate Solution. The solutions expression values are updated with the candidate expression values."/>
      </eAnnotations>
    </eOperations>
    <eOperations name="reset">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Initialiaze the solution to the zero solution (no Task is scheduled)&#xA;"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="constructExpressions"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Moves" upperBound="-1"
        eType="#//Move" containment="true" eOpposite="#//Move/Solution"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Tasks" upperBound="-1"
        eType="#//SolutionTask" containment="true" eOpposite="#//SolutionTask/Solution"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Resources" upperBound="-1"
        eType="#//SolutionResource" containment="true" eOpposite="#//SolutionResource/Solution"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CandidateMove" eType="#//Move"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Expressions" upperBound="-1"
        eType="#//CandidateValueExpression"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="SolutionNr" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Scheduler" eType="#//Scheduler"
        eOpposite="#//Scheduler/Solutions"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SolutionResource" eSuperTypes="../../com.misc.common.moplaf.propagator2/model/propagator.ecore#//ObjectWithPropagatorFunctions">
    <eOperations name="constructExpressions"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Resource" lowerBound="1"
        eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ScheduledTasks" upperBound="-1"
        eType="#//SolutionTask" eOpposite="#//SolutionTask/ScheduledResource"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CandidateScheduledTasks"
        upperBound="-1" eType="#//SolutionTask" eOpposite="#//SolutionTask/CandidateScheduledResource"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CandidateFirstTask" eType="#//SolutionTask"
        eOpposite="#//SolutionTask/ResourceAsCandidateFirstTask"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CandidateLastTask" eType="#//SolutionTask"
        eOpposite="#//SolutionTask/ResourceAsCandidateLastTask"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Expressions" upperBound="-1"
        eType="#//CandidateValueExpression"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Solution" lowerBound="1"
        eType="#//Solution" eOpposite="#//Solution/Resources"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SolutionTask" eSuperTypes="../../com.misc.common.moplaf.propagator2/model/propagator.ecore#//ObjectWithPropagatorFunctions">
    <eOperations name="unsetCandidatePreviousNext"/>
    <eOperations name="setCandidatePreviousNext">
      <eParameters name="solution" eType="#//SolutionResource"/>
      <eParameters name="previous" eType="#//SolutionTask"/>
      <eParameters name="next" eType="#//SolutionTask"/>
    </eOperations>
    <eOperations name="constructExpressions"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Task" lowerBound="1" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="NextTask" eType="#//SolutionTask"
        eOpposite="#//SolutionTask/PreviousTask"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="PreviousTask" eType="#//SolutionTask"
        eOpposite="#//SolutionTask/NextTask"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ScheduledResource" eType="#//SolutionResource"
        eOpposite="#//SolutionResource/ScheduledTasks"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CandidateNextTask" eType="#//SolutionTask"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CandidatePreviousTask"
        eType="#//SolutionTask"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ResourceAsCandidateFirstTask"
        eType="#//SolutionResource" eOpposite="#//SolutionResource/CandidateFirstTask"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ResourceAsCandidateLastTask"
        eType="#//SolutionResource" eOpposite="#//SolutionResource/CandidateLastTask"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CandidateScheduledResource"
        eType="#//SolutionResource" eOpposite="#//SolutionResource/CandidateScheduledTasks"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Expressions" upperBound="-1"
        eType="#//CandidateValueExpression"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Solution" lowerBound="1"
        eType="#//Solution" eOpposite="#//Solution/Tasks"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Move">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Expressions" upperBound="-1"
        eType="#//MoveExpression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Changes" upperBound="-1"
        eType="#//MoveChange" containment="true" eOpposite="#//MoveChange/Move"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Solution" lowerBound="1"
        eType="#//Solution" eOpposite="#//Solution/Moves"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MoveChange" abstract="true">
    <eOperations name="change" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="TaskToSchedule" lowerBound="1"
        eType="#//SolutionTask"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Valid" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Move" lowerBound="1" eType="#//Move"
        eOpposite="#//Move/Changes"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MoveChangeTask" abstract="true" eSuperTypes="#//MoveChange">
    <eStructuralFeatures xsi:type="ecore:EReference" name="InsertionPoint" lowerBound="1"
        eType="#//SolutionTask"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ScheduleAfter" eSuperTypes="#//MoveChangeTask"/>
  <eClassifiers xsi:type="ecore:EClass" name="ScheduleBefore" eSuperTypes="#//MoveChangeTask"/>
  <eClassifiers xsi:type="ecore:EClass" name="MoveChangeResource" abstract="true"
      eSuperTypes="#//MoveChange">
    <eStructuralFeatures xsi:type="ecore:EReference" name="InsertionPoint" lowerBound="1"
        eType="#//SolutionResource"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ScheduleFirst" eSuperTypes="#//MoveChangeResource"/>
  <eClassifiers xsi:type="ecore:EClass" name="ScheduleLast" eSuperTypes="#//MoveChangeResource"/>
  <eClassifiers xsi:type="ecore:EClass" name="Unschedule" eSuperTypes="#//MoveChange"/>
  <eClassifiers xsi:type="ecore:EClass" name="OwnerExpression" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Owner" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Role" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MoveExpression" abstract="true" eSuperTypes="#//OwnerExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="SolutionExpression" abstract="true"
      eSuperTypes="#//OwnerExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Solution" lowerBound="1"
        eType="#//Solution"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ResourceExpression" abstract="true"
      eSuperTypes="#//OwnerExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Resource" lowerBound="1"
        eType="#//SolutionResource"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TaskExpression" abstract="true" eSuperTypes="#//OwnerExpression">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="An Expression for a Task in a Solution.&#xA;The Expression maintains 2 values: 1) the value of the expression for the Task in the Solution and 2) the candidate value, that is the value of the Expression in the Solution resulting from performing the candidate Move on this Solution."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Task" eType="#//SolutionTask"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ValueExpression" abstract="true" eSuperTypes="#//OwnerExpression">
    <eOperations name="setValue">
      <eParameters name="candidate" eType="#//CandidateValueExpression"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FloatExpression" eSuperTypes="#//ValueExpression">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A TaskExpression, whose value Type is Float."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IntExpression" eSuperTypes="#//ValueExpression">
    <eAnnotations source="http://www.obeo.fr/dsl/dnc/archetype">
      <details key="archetype" value="MomentInterval"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="0"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DateExpression" eSuperTypes="#//ValueExpression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CandidateValueExpression" abstract="true"
      eSuperTypes="../../com.misc.common.moplaf.propagator2/model/propagator.ecore#//ObjectWithPropagatorFunctions #//ValueExpression">
    <eOperations name="refreshValueCandidate"/>
    <eOperations name="setValue"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="CandidateValueAsString"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" changeable="false"
        volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CandidateFloatExpression" eSuperTypes="#//CandidateValueExpression #//FloatExpression">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A TaskExpression, whose value Type is Float."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="CandidateValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CandidateDateExpression" eSuperTypes="#//CandidateValueExpression #//DateExpression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="CandidateValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CandidateIntExpression" eSuperTypes="#//CandidateValueExpression #//IntExpression">
    <eAnnotations source="http://www.obeo.fr/dsl/dnc/archetype">
      <details key="archetype" value="MomentInterval"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="CandidateValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="0"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TaskCandidateDateExpression" eSuperTypes="#//CandidateDateExpression #//TaskExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="TaskCandidateFloatExpression" eSuperTypes="#//CandidateFloatExpression #//TaskExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="TaskCandidateIntExpression" eSuperTypes="#//CandidateIntExpression #//TaskExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="ResourceCandidateDateExpression" eSuperTypes="#//CandidateDateExpression #//ResourceExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="ResourceCandidateFloatExpression" eSuperTypes="#//CandidateFloatExpression #//ResourceExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="ResourceCandidateIntExpression" eSuperTypes="#//CandidateIntExpression #//ResourceExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="SolutionCandidateDateExpression" eSuperTypes="#//CandidateDateExpression #//SolutionExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="SolutionCandidateFloatExpression" eSuperTypes="#//CandidateFloatExpression #//SolutionExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="SolutionCandidateIntExpression" eSuperTypes="#//CandidateIntExpression #//SolutionExpression"/>
</ecore:EPackage>
