<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="schedulercalc" nsURI="http://www.misc.com/common/moplaf/scheduler/calc/model/0.1"
    nsPrefix="schedc">
  <eClassifiers xsi:type="ecore:EClass" name="SolutionPropagatorFunction" eSuperTypes="../../com.misc.common.moplaf.propagator2/model/propagator.ecore#//PropagatorFunctionBindings">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Solution" lowerBound="1"
        eType="ecore:EClass scheduler.ecore#//Solution" changeable="false" volatile="true"
        transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SolutionExpressionPropagatorFunction"
      eSuperTypes="../../com.misc.common.moplaf.propagator2/model/propagator.ecore#//PropagatorFunctionBindings">
    <eStructuralFeatures xsi:type="ecore:EReference" name="SolutionExpression" lowerBound="1"
        eType="ecore:EClass scheduler.ecore#//SolutionExpression" changeable="false"
        volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ResourcePropagatorFunction" eSuperTypes="../../com.misc.common.moplaf.propagator2/model/propagator.ecore#//PropagatorFunctionBindings">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Resource" lowerBound="1"
        eType="ecore:EClass scheduler.ecore#//SolutionResource" changeable="false"
        volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ResourceExpressionPropagatorFunction"
      eSuperTypes="../../com.misc.common.moplaf.propagator2/model/propagator.ecore#//PropagatorFunctionBindings">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ResourceExpression" lowerBound="1"
        eType="ecore:EClass scheduler.ecore#//ResourceExpression" changeable="false"
        volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TaskPropagatorFunction" eSuperTypes="../../com.misc.common.moplaf.propagator2/model/propagator.ecore#//PropagatorFunctionBindings">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Task" lowerBound="1" eType="ecore:EClass scheduler.ecore#//SolutionTask"
        changeable="false" volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TaskExpressionPropagatorFunction" eSuperTypes="../../com.misc.common.moplaf.propagator2/model/propagator.ecore#//PropagatorFunctionBindings">
    <eStructuralFeatures xsi:type="ecore:EReference" name="TaskExpression" lowerBound="1"
        eType="ecore:EClass scheduler.ecore#//TaskExpression" changeable="false" volatile="true"
        transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SetTaskCandidateScheduledResourceScope"
      eSuperTypes="#//SolutionPropagatorFunction"/>
  <eClassifiers xsi:type="ecore:EClass" name="SetTaskCandidateScheduledResource" eSuperTypes="#//TaskPropagatorFunction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ConcreteParent" lowerBound="1"
        eType="#//SetTaskCandidateScheduledResourceScope" changeable="false" volatile="true"
        transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SetExpressionCandidateValueScope" eSuperTypes="#//SolutionPropagatorFunction"/>
  <eClassifiers xsi:type="ecore:EClass" name="SetTaskExpressionCandidateValue" eSuperTypes="#//TaskExpressionPropagatorFunction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ConcreteParent" lowerBound="1"
        eType="#//SetExpressionCandidateValueScope" changeable="false" volatile="true"
        transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SetSolutionExpressionCandidateValue"
      eSuperTypes="#//SolutionExpressionPropagatorFunction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ConcreteParent" lowerBound="1"
        eType="#//SetExpressionCandidateValueScope" changeable="false" volatile="true"
        transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SetResourceExpressionCandidateValue"
      eSuperTypes="#//ResourceExpressionPropagatorFunction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ConcreteParent" lowerBound="1"
        eType="#//SetExpressionCandidateValueScope" changeable="false" volatile="true"
        transient="true" derived="true"/>
  </eClassifiers>
</ecore:EPackage>
